version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: bash/before_deployment.sh
  AfterInstall:
    - location: bash/after_deployment.sh
      timeout: 20
  ApplicationStart:
    - location: bash/functional_test.sh
      timeout: 20
  ValidateService:
    - location: bash/monitor.sh
      timeout: 20
